version: '3.8'

services:
  react_app:
    build: .
    container_name: react_app
    ports:
      - "8087:8087"
    restart: always
    volumes:
      - ./nginx.config:/etc/nginx/conf.d/default.conf
